# Generated by Django 2.1 on 2018-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180810_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Emprestimo'),
        ),
    ]
