# Generated by Django 2.1 on 2018-08-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180810_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
    ]
