# Generated by Django 2.1 on 2018-08-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_emprestimo_devolvido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Reserva Ativa ?'),
        ),
    ]
