# Generated by Django 2.1 on 2018-08-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180810_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'ordering': ['nome']},
        ),
    ]
