# Generated by Django 2.0.4 on 2018-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180812_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='categoria',
            field=models.CharField(max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='editora',
            field=models.CharField(max_length=255, verbose_name='Editora'),
        ),
    ]
