# Generated by Django 2.0.4 on 2018-08-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180812_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Estoque'),
        ),
    ]
