# Generated by Django 2.0.4 on 2018-08-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_emprestimo_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='titulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='core.Titulo', verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
