# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171215_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='core/static/images', verbose_name='Imagem'),
        ),
    ]
