# Generated by Django 2.0.4 on 2018-05-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addrees',
            new_name='Address',
        ),
    ]
