# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171125_2259'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaodiaria',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='solicitacaodiaria',
            name='diarias',
        ),
        migrations.RemoveField(
            model_name='solicitacaodiaria',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='solicitacaodiaria',
            name='retorno',
        ),
        migrations.RemoveField(
            model_name='solicitacaodiaria',
            name='viagens',
        ),
        migrations.AddField(
            model_name='solicitacaodiaria',
            name='memo',
            field=models.CharField(default=' ', max_length=5, verbose_name='memorando'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodiaria',
            name='viagem',
            field=models.ManyToManyField(to='core.Viagem'),
        ),
    ]
