# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171126_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaodiaria',
            options={'verbose_name': 'Solicitação de Diaria', 'verbose_name_plural': 'Solicitações de Diarias'},
        ),
        migrations.AlterField(
            model_name='solicitacaodiaria',
            name='memo',
            field=models.CharField(max_length=5, verbose_name='Memorando'),
        ),
    ]
