# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_viagem_is_relatorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polo',
            options={'verbose_name': 'Polo', 'verbose_name_plural': 'Polos'},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
    ]
