# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171126_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=5, verbose_name='Memorando')),
                ('viagem', models.ManyToManyField(to='core.Viagem')),
            ],
            options={
                'verbose_name': 'Solicitação de Diaria',
                'verbose_name_plural': 'Solicitações de Diarias',
            },
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do Veiculo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo_de_veiculo',
            field=models.CharField(blank=True, choices=[('O', 'Oficial'), ('L', 'Locado'), ('P', 'Proprio'), ('T', 'Outros')], max_length=1, null=True, verbose_name='Tipo de Veiculo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='transporte',
            field=models.CharField(blank=True, choices=[('M', 'Moto'), ('C', 'Carro'), ('B', 'Onibus'), ('Z', 'Aviao'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Meio de Transporte'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='viagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='core.Viagem', verbose_name='Viagem'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Genero'),
        ),
    ]
