# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171215_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='image',
            field=models.ImageField(blank=True, upload_to='core/static/images', verbose_name='Imagem'),
        ),
    ]
