# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180111_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.Curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tipo',
            field=models.CharField(choices=[('F', 'Professor Formador'), ('C', 'Coordenador do Curso'), ('T', 'Tutor')], default='T', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
