# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180111_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='formacao',
            field=models.CharField(choices=[('D', 'Doutor'), ('M', 'Mestre'), ('E', 'Especialista'), ('O', 'Outros')], default='O', max_length=2, null=True, verbose_name='Formacao'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tipo_conta',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança')], max_length=2, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tipo',
            field=models.CharField(choices=[('T', 'Tutor'), ('CG', 'Coordenador Geral'), ('CC', 'Coordenador Curso'), ('CT', 'Coordenador de Tutoria'), ('CP', 'Coordenador de Polo'), ('PF', 'Professor Formador'), ('PC', 'Professor Conteudista'), ('AD', 'Assistente a Docencia'), ('O', 'Outros')], default='T', max_length=2, null=True, verbose_name='Tipo'),
        ),
    ]
