# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_viagem_is_ajuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodiaria',
            name='viagem',
            field=models.ManyToManyField(related_name='solicitacoes', to='core.Viagem'),
        ),
    ]
