# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_solicitacaodiaria_justificativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero do Memorando')),
                ('assunto', models.CharField(max_length=40, verbose_name='Assunto')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('destinatario', models.CharField(default=' Diretoria do Centro de Educação Aberta e à Distância - CEAD/UFPI', max_length=80, verbose_name='Destinatario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Memorando',
                'verbose_name_plural': 'Memorandos',
            },
        ),
        # migrations.AlterField(
        #     model_name='solicitacaodiaria',
        #     name='memo',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Memorando', verbose_name='Memorando'),
        # ),
    ]
