# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180220_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaodiaria',
            old_name='memo',
            new_name='memorando',
        ),
    ]
