# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 00:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome do Polo')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_da_viagem', models.TextField(verbose_name='Dados da Viagem')),
                ('tipo', models.CharField(choices=[('N', 'Nacionais'), ('I', 'Internacionais')], max_length=1, null=True, verbose_name='Tipo de de Diaria')),
                ('resultados', models.TextField(verbose_name='Resultados Alcançados')),
            ],
            options={
                'verbose_name': 'Relatorio',
                'verbose_name_plural': 'Relatorios',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, null=True, verbose_name='Nome Completo')),
                ('pais', models.CharField(max_length=35)),
                ('cidade', models.CharField(max_length=35)),
                ('bairro', models.CharField(max_length=35)),
                ('logradouro', models.CharField(blank=True, max_length=35)),
                ('numero', models.CharField(max_length=35)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d{8}$|^\\d{5}-\\d{3}$', 32), code='invalid', message='Informe um cep valido no formato 88888888 ou 88888-888')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Genero')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('banco', models.CharField(max_length=25, verbose_name='Nome do Banco')),
                ('agencia', models.CharField(max_length=12, verbose_name='Agencia Bancaria')),
                ('conta', models.CharField(max_length=12, verbose_name='Numero da Conta')),
                ('rg', models.CharField(blank=True, max_length=15, null=True, verbose_name='RG')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('expedidor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Orgao Expedidor')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='core.Polo', verbose_name='Polo')),
            ],
            options={
                'verbose_name': 'Tutor(a)',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.DateField(verbose_name='Data de Ida')),
                ('retorno', models.DateField(verbose_name='Data de retorno')),
                ('origem', models.CharField(max_length=25, verbose_name='Cidade de Origem')),
                ('is_solicited', models.BooleanField(default=False)),
                ('diarias', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('((0)|(1)|(2)|(3)|(4)){1}[.]((0)|(5))', 32), code='invalid', message='Informe a diaria no formato X,X exemplo: 1.5')])),
                ('polo', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='core.Polo', verbose_name='Cidade de Destino')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='core.Tutor', verbose_name='tutor')),
            ],
        ),
    ]
