# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='viagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Viagem', verbose_name='Viagem'),
        ),
    ]
