# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171126_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='bilhete_ida',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bilhete de Ida'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='bilhete_volta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bilhete de Volta'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='nome_do_condutor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nome do condutor'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Nome do condutor'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tipo_de_veiculo',
            field=models.CharField(blank=True, choices=[('O', 'Oficial'), ('L', 'Locado'), ('P', 'Proprio'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Tipo de Veiculo'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='transporte',
            field=models.CharField(blank=True, choices=[('M', 'Moto'), ('C', 'Carro'), ('O', 'Onibus'), ('A', 'Aviao'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Meio de Transporte'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('N', 'Nacionais'), ('I', 'Internacionais')], max_length=1, null=True, verbose_name='Tipo de Diaria'),
        ),
    ]
