# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 13:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Colaborador(a)', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='diarias',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('((0)|(1)|(2)|(3)|(4)){1}[.]((0)|(5))', 32), code='invalid', message='Informe a diaria no formato X.X exemplo: 1.5')]),
        ),
    ]
