# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180112_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='is_ajuda',
            field=models.BooleanField(default=False, verbose_name='Ajuda com o transporte'),
        ),
    ]
