# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180114_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(upload_to='core/static/images', verbose_name='Imagem'),
        ),
    ]
