# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180220_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodiaria',
            name='memorando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Memorando', verbose_name='Memorando'),
        ),
    ]
