# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180220_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='assunto',
            field=models.TextField(verbose_name='Assunto'),
        ),
    ]
