# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180307_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='nome_do_condutor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do condutor'),
        ),
    ]
