# Generated by Django 2.1 on 2018-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('BIBLIOTECÁRIO', 'Bibliotecário'), ('USUARIO', 'Usuário')], default='USUARIO', max_length=255, verbose_name='Tipo do Usuário'),
        ),
    ]
