# Generated by Django 2.1 on 2018-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180810_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('BIBLIOTECÁRIO', 'BIBLIOTECÁRIO'), ('USUÁRIO', 'USUÁRIO')], default='USUARIO', max_length=255, verbose_name='Tipo do Usuário'),
        ),
    ]
